#!/usr/bin/env python
import pika
import sys
import os
import json
import yaml


#getting configuration
stream = open("/etc/serf/handlers/configuration.yml", 'r')
conf = yaml.load(stream)


payload = ""
event=os.environ['SERF_EVENT']

for line in sys.stdin:
      payload += line

message = {
  "self" : os.environ['SERF_SELF_NAME'],
  "payload": payload,
}

credentials = pika.PlainCredentials(conf['rabbitmq']['user'], conf['rabbitmq']['password'])
connection = pika.BlockingConnection(pika.ConnectionParameters(host=conf['rabbitmq']['host'], credentials=credentials))
channel = connection.channel()

channel.exchange_declare(exchange='events', type='topic')

channel.basic_publish(exchange='events', routing_key=event, body=json.dumps(message))
connection.close()
