#!/bin/bash
SERFDIR="/etc/serf"


if [ "$SERF_EVENT" == "user" ]; then
  EVENT="user-$SERF_USER_EVENT"
elif [ "$SERF_EVENT" == "query" ]; then
  EVENT="query-$SERF_QUERY_NAME"
else
  EVENT=$SERF_EVENT
fi

HANDLER="$SERFDIR/handlers/$EVENT"

[ -f "$HANDLER" -a -x "$HANDLER" ] && exec "$HANDLER" || :
