#!/bin/bash

# Common functions for contextualization scripts

function set_distribution {
# Check the distribution
    DISTRIBUTION=

    if [ -x /usr/bin/lsb_release ];then
        dist=$(/usr/bin/lsb_release -i|cut -f 2)
        case $dist in
            Debian )
                DISTRIBUTION="debian"
            ;;
            Ubuntu )
                DISTRIBUTION="debian"
            ;;
            CentOS )
                DISTRIBUTION="centos"
            ;;
        esac
    fi

#no lsb_release, try detection of distribution-specific files
    if [ ! $DISTRIBUTION ];then
        if [ -d "/etc/sysconfig" ];then
            DISTRIBUTION="centos"
        elif [ -f "/etc/network/interfaces" ];then
            DISTRIBUTION="debian"
        fi
    fi

}

function add_ssh_key {
    if [ "$AUTHORIZED_KEYS" ];then
        # create directory if it does not exist
        test -d /root/.ssh || mkdir /root/.ssh && touch /root/.ssh/authorized_keys
        chmod 700 /root/.ssh
        echo ${AUTHORIZED_KEYS} | while read key; do
            # check if the key is already in there
            grep -q "${key}" /root/.ssh/authorized_keys && continue;
            # else, add the key
            echo "${key}" >> /root/.ssh/authorized_keys
        done
    fi
}
