set :snoozenode_deb_url, "https://ci.inria.fr/snooze-software/job/testing-snoozenode/ws/distributions/deb-package/snoozenode_1.1.0-0_all.deb"
set :snoozeclient_deb_url, "https://ci.inria.fr/snooze-software/job/testing-snoozeclient/ws/distributions/deb-package/snoozeclient_1.1.0-0_all.deb"
set :snooze_capistrano_branch, "testing"
#set :snoozenode_deb_url, "http://public.nancy.grid5000.fr/~msimonin/snooze/testing/snoozenode_1.1.0-0_all.deb"
#set :snoozeclient_deb_url, "http://public.nancy.grid5000.fr/~msimonin/snooze/testing/snoozeclient_1.1.0-0_all.deb"
